Ejemplo de lectura desde Excel

conda install xlrd

In [1]:
import pandas as pd
archivo_excel = pd.read_excel('../DataSets/Terrenos Mendoza.xlsx')
print(archivo_excel.columns)

columnas = ['#', 'Luz', 'Agua', 'Gas', 'Cloacas', 'Suelo', 'Contexto urbano',
       'Permeabilidad', 'usd mt2', ' usd Total ', 'Superficie', 'Distrito',
       'Latitud', 'Longuitud', 'Derecho de agua', 'Coordenadas']
df_seleccionados = archivo_excel[columnas]

df_seleccionados.head()

Index(['#', 'Luz', 'Agua', 'Gas', 'Cloacas', 'Suelo', 'Contexto urbano',
       'Permeabilidad', 'usd mt2', ' usd Total ', 'Superficie', 'Distrito',
       'Latitud', 'Longuitud', 'Derecho de agua', 'Coordenadas'],
      dtype='object')

,#,Luz,Agua,Gas,Cloacas,Suelo,Contexto urbano,Permeabilidad,usd mt2,usd Total,Superficie,Distrito,Latitud,Longuitud,Derecho de agua,Coordenadas
0,1,1,1,1,0,Interfaz,Bº Privado en Desarrollo,Baldio,61.643836,27000,438,Mayor Drummond,-33.0138,-68.8321,si,-68.83213;-33.01380
1,2,1,1,1,0,Interfaz,Bº Privado en Desarrollo,Baldio,32.248607,11609.5,360,Otros,-33.0603,-68.8672,si,-68.867228;-33.060311
2,3,1,1,1,0,Interfaz,Bº Privado en Desarrollo,Baldio,32.090138,11873.4,370,Otros,-33.0603,-68.8672,si,-68.867228;-33.060311
3,4,1,1,1,0,Interfaz,Bº Privado en Desarrollo,Baldio,36.499560,10949.9,300,Otros,-33.0623,-68.8699,si,-68.86992;-33.06230
4,6,1,1,1,0,Otro,Conexo a urbanización,Natural,91.525424,27000,295,Otros,-32.9629,-68.8699,no,-68.869854;-32.962940